apiVersion: v2
appVersion: '1.0'
description: A Helm chart for cnp-plum-frontend App
name: cnp-plum-frontend
home: https://github.com/hmcts/cnp-plum-frontend
version: 0.0.2
dependencies:
  - name: nodejs
    version: 2.4.16
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
